version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven
      - apt-get update
      - apt-get install -y maven

  build:
    commands:
      - echo Building the project
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/*.jar
