version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven
      - apt-get update
      - apt-get install -y maven

  pre_build:
    commands:
      - echo Logging in to GitHub
      - git clone https://github.com/sylvestra81/aws-codepipeline.git

  build:
    commands:
      - echo Build started
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/*.jar
